use crate::models::{ChangedFile, Task, VerificationRun, VerificationStatus};
use std::fmt::Write as _;

pub fn render(
    task: &Task,
    changed: &[ChangedFile],
    latest_run: Option<&VerificationRun>,
) -> String {
    let mut out = String::new();
    writeln!(out, "# AI Software Studio Evidence Report").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "## Task").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "**{}** (`{}`)", task.title, task.id).unwrap();
    writeln!(out).unwrap();

    if !task.description.trim().is_empty() {
        writeln!(out, "{}", task.description.trim()).unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "## Acceptance Criteria").unwrap();
    writeln!(out).unwrap();
    if task.acceptance_criteria.is_empty() {
        writeln!(out, "_None defined._").unwrap();
    } else {
        for ac in &task.acceptance_criteria {
            let mark = if ac.satisfied { "x" } else { " " };
            writeln!(out, "- [{mark}] {}", ac.label).unwrap();
        }
    }
    writeln!(out).unwrap();

    writeln!(out, "## Files Changed").unwrap();
    writeln!(out).unwrap();
    if changed.is_empty() {
        writeln!(out, "_No changed files detected._").unwrap();
    } else {
        writeln!(out, "| File | Status |").unwrap();
        writeln!(out, "|---|---|").unwrap();
        for c in changed {
            writeln!(out, "| `{}` | {:?} |", c.path, c.status).unwrap();
        }
    }
    writeln!(out).unwrap();

    writeln!(out, "## Verification").unwrap();
    writeln!(out).unwrap();
    match latest_run {
        None => writeln!(out, "_No verification run yet._").unwrap(),
        Some(run) => {
            writeln!(out, "Run `{}` started at {}.", run.id, run.started_at).unwrap();
            writeln!(out).unwrap();
            writeln!(out, "| Check | Status | Duration |").unwrap();
            writeln!(out, "|---|---|---|").unwrap();
            for c in &run.checks {
                let badge = match c.status {
                    VerificationStatus::Passed => "✅ passed",
                    VerificationStatus::Failed => "❌ failed",
                    VerificationStatus::Skipped => "⏭ skipped",
                    VerificationStatus::Warning => "⚠️ warning",
                    VerificationStatus::Running => "⏳ running",
                    VerificationStatus::NotRun => "— not run",
                };
                let dur = c
                    .duration_ms
                    .map(|m| format!("{m}ms"))
                    .unwrap_or_else(|| "—".to_string());
                writeln!(out, "| {} | {} | {} |", c.kind, badge, dur).unwrap();
            }
        }
    }
    writeln!(out).unwrap();

    if !task.constraints.is_empty() {
        writeln!(out, "## Constraints").unwrap();
        writeln!(out).unwrap();
        for c in &task.constraints {
            writeln!(out, "- {c}").unwrap();
        }
        writeln!(out).unwrap();
    }

    writeln!(out, "---").unwrap();
    writeln!(out, "Generated by AI Software Studio · task `{}`", task.id).unwrap();

    out
}
