use crate::{artifacts, error::AppError, models::Task};
use std::fmt::Write as _;

pub fn render_brief(task: &Task) -> String {
    let mut out = String::new();
    writeln!(out, "# {}", task.title).unwrap();
    writeln!(out).unwrap();

    if !task.description.trim().is_empty() {
        writeln!(out, "## Description").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "{}", task.description.trim()).unwrap();
        writeln!(out).unwrap();
    }

    if !task.acceptance_criteria.is_empty() {
        writeln!(out, "## Acceptance Criteria").unwrap();
        writeln!(out).unwrap();
        for ac in &task.acceptance_criteria {
            let mark = if ac.satisfied { "x" } else { " " };
            writeln!(out, "- [{mark}] {}", ac.label).unwrap();
        }
        writeln!(out).unwrap();
    }

    if !task.constraints.is_empty() {
        writeln!(out, "## Constraints").unwrap();
        writeln!(out).unwrap();
        for c in &task.constraints {
            writeln!(out, "- {c}").unwrap();
        }
        writeln!(out).unwrap();
    }

    if !task.out_of_scope.trim().is_empty() {
        writeln!(out, "## Out of Scope").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "{}", task.out_of_scope.trim()).unwrap();
        writeln!(out).unwrap();
    }

    if !task.files_to_touch_hint.trim().is_empty() {
        writeln!(out, "## Files to Touch").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "{}", task.files_to_touch_hint.trim()).unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "---").unwrap();
    writeln!(out, "Generated by AI Software Studio · task `{}`", task.id).unwrap();

    out
}

/// Write `task-brief.md` into the durable artifact store for the task.
pub fn write_brief(task: &Task) -> Result<(), AppError> {
    let dir = artifacts::artifact_dir(&task.project_id, &task.id)?;
    let path = dir.join("task-brief.md");
    std::fs::write(&path, render_brief(task))
        .map_err(|e| AppError::internal(format!("write brief: {e}")))?;
    Ok(())
}
